# Generated by Django 4.2.9 on 2024-02-04 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pr_tracking_web", "0003_rename_exercise_exercise_exercise_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentPersonalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gym_rat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workout_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("exercise_name", models.CharField(max_length=128)),
                ("weight", models.IntegerField()),
                ("reps", models.IntegerField()),
                ("performed_at", models.DateTimeField(auto_now=True)),
                (
                    "gym_rat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameModel(old_name="Workout", new_name="DesignedWorkout"),
        migrations.AddField(
            model_name="exercise",
            name="body_part",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="exercise",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(name="Performance"),
        migrations.AddField(
            model_name="currentpersonalrecord",
            name="pr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="pr_tracking_web.setinstance",
            ),
        ),
    ]
