# Generated by Django 4.2.9 on 2024-03-29 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pr_tracking_web", "0006_exercisetemplate_workouttemplate_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="setinstance", old_name="reps", new_name="reps_completed"),
        migrations.RemoveField(model_name="setinstance", name="exercise_name"),
        migrations.RemoveField(model_name="setinstance", name="gym_rat"),
        migrations.RemoveField(model_name="setinstance", name="performed_at"),
        migrations.RemoveField(model_name="setinstance", name="workout_name"),
        migrations.AddField(
            model_name="setinstance",
            name="skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="WorkoutInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "gym_rat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pr_tracking_web.workouttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pr_tracking_web.exercisetemplate",
                    ),
                ),
                (
                    "workout_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pr_tracking_web.workoutinstance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="setinstance",
            name="exercise_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pr_tracking_web.exerciseinstance",
            ),
        ),
    ]
