run:
    poetry run python manage.py runserver
make-migrations:
    poetry run python manage.py makemigrations
migrate:
    poetry run python manage.py migrate
create-superuser:
    poetry run python manage.py createsuperuser
