# Generated by Django 4.2.9 on 2024-04-25 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseOutline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number_of_sets", models.IntegerField()),
                ("number_of_reps", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutOutline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workout_outline_name", models.CharField(max_length=128)),
                (
                    "gym_rat",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "gym_rat",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "workout_outline",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="swole_stats_api.workoutoutline"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weight", models.IntegerField()),
                ("reps_completed", models.IntegerField()),
                ("volume", models.IntegerField()),
                ("skipped", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise_outline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="swole_stats_api.exerciseoutline"
                    ),
                ),
                (
                    "workout_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="swole_stats_api.workoutrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotionalExercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exercise_name", models.CharField(max_length=128)),
                (
                    "primary_muscle_group",
                    models.CharField(
                        choices=[
                            ("SHOULDERS", "SHOULDERS"),
                            ("BACK", "BACK"),
                            ("CHEST", "CHEST"),
                            ("ARMS", "ARMS"),
                            ("LEGS", "LEGS"),
                            ("CORE", "CORE"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "secondary_muscle_groups",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SHOULDERS", "SHOULDERS"),
                            ("BACK", "BACK"),
                            ("CHEST", "CHEST"),
                            ("ARMS", "ARMS"),
                            ("LEGS", "LEGS"),
                            ("CORE", "CORE"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "exercise_scope",
                    models.CharField(choices=[("ISOLATION", "ISOLATION"), ("COMPOUND", "COMPOUND")], max_length=128),
                ),
                (
                    "equipment_category",
                    models.CharField(
                        choices=[
                            ("DUMBELL", "DUMBELL"),
                            ("BARBELL", "BARBELL"),
                            ("MACHINE", "MACHINE"),
                            ("CABLES", "CABLES"),
                            ("KETTLEBELL", "KETTLEBELL"),
                        ],
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "gym_rat",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exerciseoutline",
            name="notional_exercise",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="swole_stats_api.notionalexercise"),
        ),
        migrations.AddField(
            model_name="exerciseoutline",
            name="workout_outline",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="swole_stats_api.workoutoutline"),
        ),
    ]
