setup-dev:
    docker-compose up --build
    poetry install

lint:
    pre-commit run --all-files

run:
    docker-compose up --build # TODO: fix this to use volumes, atm we need to rebuild the container to catch any frontend changes (maybe even backend I haven't tried)

make-migrations:
    docker-compose run web /root/.local/bin/poetry run python monolith/manage.py makemigrations

migrate:
    docker-compose run web /root/.local/bin/poetry run python monolith/manage.py migrate

create-superuser:
    docker-compose run web /root/.local/bin/poetry run python monolith/manage.py createsuperuser
