# Generated by Django 4.2.9 on 2024-02-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pr_tracking_web", "0004_currentpersonalrecord_setinstance_and_more")]

    operations = [
        migrations.AddField(
            model_name="designedworkout",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        )
    ]
