# Generated by Django 4.2.9 on 2024-04-26 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("swole_stats_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notionalexercise",
            name="gym_rat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="exercises", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
