# Generated by Django 4.2.9 on 2024-04-27 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("swole_stats_api", "0002_alter_notionalexercise_gym_rat"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutoutline",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="exerciseoutline",
            name="notional_exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_outlines",
                to="swole_stats_api.notionalexercise",
            ),
        ),
        migrations.AlterField(
            model_name="exerciseoutline",
            name="workout_outline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_outlines",
                to="swole_stats_api.workoutoutline",
            ),
        ),
        migrations.AlterField(
            model_name="setrecord",
            name="exercise_outline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_records",
                to="swole_stats_api.exerciseoutline",
            ),
        ),
        migrations.AlterField(
            model_name="setrecord",
            name="workout_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_records",
                to="swole_stats_api.workoutrecord",
            ),
        ),
        migrations.AlterField(
            model_name="workoutoutline",
            name="gym_rat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="workout_outline", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="workoutrecord",
            name="gym_rat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="workout_records", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="workoutrecord",
            name="workout_outline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_records",
                to="swole_stats_api.workoutoutline",
            ),
        ),
    ]
