# Generated by Django 4.2.9 on 2024-05-07 04:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swole_stats_api", "0004_alter_setrecord_reps_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notionalexercise",
            name="secondary_muscle_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("SHOULDERS", "SHOULDERS"),
                        ("BACK", "BACK"),
                        ("CHEST", "CHEST"),
                        ("ARMS", "ARMS"),
                        ("LEGS", "LEGS"),
                        ("CORE", "CORE"),
                    ],
                    max_length=128,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
