# Generated by Django 4.2.9 on 2024-04-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swole_stats_api", "0003_workoutoutline_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setrecord",
            name="reps_completed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="setrecord",
            name="volume",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="setrecord",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
