# Generated by Django 4.1.6 on 2023-06-15 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "pr_tracking_web",
            "0002_remove_performance_date_performance_created_at_and_more",
        )
    ]

    operations = [migrations.RenameField(model_name="exercise", old_name="exercise", new_name="exercise_name")]
