# Generated by Django 4.2.9 on 2024-03-24 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pr_tracking_web", "0005_designedworkout_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_sets", models.IntegerField()),
                ("number_of_reps", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pr_tracking_web.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workout_template_name", models.CharField(max_length=128)),
                (
                    "gym_rat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="DesignedWorkout"),
        migrations.AddField(
            model_name="exercisetemplate",
            name="workout_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pr_tracking_web.workouttemplate",
            ),
        ),
    ]
